#!/usr/bin/env node
/**
 * Prepare a self-contained published dsh runtime in the user's cache.
 * This is intentionally independent from any dsh source checkout.
 */
import { existsSync } from 'node:fs'
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { spawn } from 'node:child_process'

export const RUNTIME_VERSION = '0.0.1-rc.5'
export const DEFAULT_RUNTIME_ROOT = join(process.env.XDG_CACHE_HOME || join(homedir(), '.cache'), 'deepseek-harness-subagent', 'runtime')

const PACKAGES = {
  'tsx': '^4.19.2',
  '@deepseek-ai/cordis': '^4.0.1-rc.4',
  '@deepseek-ai/dsh-invariants': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-sdk-client': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-sdk-jsonrpc-server': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-sdk-jsonrpc-demo': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-llm-deepseek': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-agent-spine-demo': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-settings-file': '^0.0.1-rc.3',
  '@deepseek-ai/dsh-credentials-local': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-fs-local': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-fs-observation-policy': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-tool-fs': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-subprocess-local': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-bash-local': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-session-persistence-jsonl': `^${RUNTIME_VERSION}`,
  '@deepseek-ai/dsh-session-checkpoint-policy': `^${RUNTIME_VERSION}`,
}

const CORDIS = `# Generated by deepseek-harness-subagent. Do not edit.\n- id: sdk-jsonrpc-server\n  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'\n- id: llm-deepseek\n  name: '@deepseek-ai/dsh-llm-deepseek'\n  config:\n    thinking: enabled\n- id: settings\n  name: '@deepseek-ai/dsh-settings-file'\n- id: credentials\n  name: '@deepseek-ai/dsh-credentials-local'\n- id: agent-spine\n  name: '@deepseek-ai/dsh-agent-spine-demo'\n  config:\n    workspaceContext: false\n    skills:\n      enabled: false\n- id: fs-local\n  name: '@deepseek-ai/dsh-fs-local'\n  config:\n    cwd: !!js process.env.DSH_CWD ?? process.cwd()\n- id: fs-observation-policy\n  name: '@deepseek-ai/dsh-fs-observation-policy'\n- id: tool-fs\n  name: '@deepseek-ai/dsh-tool-fs'\n- id: subprocess\n  name: '@deepseek-ai/dsh-subprocess-local'\n- id: bash\n  name: '@deepseek-ai/dsh-bash-local'\n  config:\n    cwd: !!js process.env.DSH_CWD ?? process.cwd()\n    timeoutMs: 60000\n- id: sessions\n  name: '@deepseek-ai/dsh-session-persistence-jsonl'\n  config:\n    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'\n- id: session-checkpoints\n  name: '@deepseek-ai/dsh-session-checkpoint-policy'\n`

function run(command, args, cwd) {
  return new Promise((resolveRun, reject) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit' })
    child.once('error', reject)
    child.once('exit', (code) => code === 0 ? resolveRun() : reject(new Error(`${command} exited with ${code}`)))
  })
}

export async function ensureRuntime(root = DEFAULT_RUNTIME_ROOT, { install = true } = {}) {
  const runtimeRoot = resolve(root)
  const marker = join(runtimeRoot, '.ready.json')
  const cordis = join(runtimeRoot, 'cordis.yml')
  try {
    const ready = JSON.parse(await readFile(marker, 'utf8'))
    if (ready.version === RUNTIME_VERSION && existsSync(join(runtimeRoot, 'node_modules', '@deepseek-ai', 'dsh-sdk-client'))) {
      return { root: runtimeRoot, nodeModules: join(runtimeRoot, 'node_modules'), cordis, runtimeBin: join(runtimeRoot, 'node_modules', '@deepseek-ai', 'dsh-sdk-jsonrpc-demo', 'lib', 'bin.js'), cached: true }
    }
  } catch {}
  if (!install) return { root: runtimeRoot, nodeModules: join(runtimeRoot, 'node_modules'), cordis, runtimeBin: join(runtimeRoot, 'node_modules', '@deepseek-ai', 'dsh-sdk-jsonrpc-demo', 'lib', 'bin.js'), cached: false, ready: false }
  await mkdir(runtimeRoot, { recursive: true })
  const packageJson = join(runtimeRoot, 'package.json')
  await writeFile(packageJson, `${JSON.stringify({ name: 'deepseek-harness-subagent-runtime', private: true, type: 'module', dependencies: PACKAGES }, null, 2)}\n`)
  try {
    await run(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['install', '--no-fund', '--no-audit', '--ignore-scripts'], runtimeRoot)
    await writeFile(cordis, CORDIS)
    const temporary = `${marker}.tmp-${process.pid}`
    await writeFile(temporary, `${JSON.stringify({ version: RUNTIME_VERSION, packages: PACKAGES })}\n`)
    await rename(temporary, marker)
  } catch (error) {
    await rm(marker, { force: true })
    throw new Error(`无法自动准备 dsh Node runtime（缓存目录：${runtimeRoot}）：${error instanceof Error ? error.message : String(error)}`)
  }
  return { root: runtimeRoot, nodeModules: join(runtimeRoot, 'node_modules'), cordis, runtimeBin: join(runtimeRoot, 'node_modules', '@deepseek-ai', 'dsh-sdk-jsonrpc-demo', 'lib', 'bin.js'), cached: false }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try { process.stdout.write(`${JSON.stringify(await ensureRuntime())}\n`) }
  catch (error) { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1 }
}
